import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import { getAnimals } from '../../../database/animals';
import { getValidSession } from '../../../database/sessions';
import AnimalsForm from './AnimalsForm';

export const metadata = {
  title: 'Animals Dashboard page',
  description: 'Generated by create next app',
};

export default async function Dashboard() {
  // Task: Add redirect to home if user is logged in

  // 1. Checking if the sessionToken cookie exists
  const sessionTokenCookie = cookies().get('sessionToken');

  // 2. Check if the sessionToken cookie is still valid
  const session =
    sessionTokenCookie && (await getValidSession(sessionTokenCookie.value));

  //  Query your database to check if this user has the right access to this page

  // 3. If the sessionToken cookie is invalid or doesn't exist, redirect to login with returnTo
  if (!session) redirect('/login?returnTo=/animals/dashboard');

  // 4. If the sessionToken cookie is valid, allow access to dashboard page
  const animals = await getAnimals(session.token);

  return <AnimalsForm animals={animals} />;
}
