import { getAnimals } from '../../database/animals';
import AnimalsForm from './AnimalsForm';

export const metadata = {
  title: 'Animal Admin page',
  description: 'Generated by create next app',
};

export default async function AnimalsPage() {
  const animals = await getAnimals();

  return <AnimalsForm animals={animals} />;
}
