import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Home page | UpLeveled', template: '%s | UpLeveled' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div>
            {/* This is not optimized */}
            {/* <a href="/">Home</a> */}
            {/* This is optimized */}
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/animals">Animals</Link>
          </div>

          {Math.floor(Math.random() * 10)}
        </nav>

        {children}
      </body>
    </html>
  );
}
